name: SnapshotTesting
options:
  bundleIdPrefix: co.pointfree
  deploymentTarget:
    iOS: 10.0
    macOS: '10.10'
    tvOS: 10.0
  indentWidth: 2
  tabWidth: 2
  usesTabs: false
targets:
  SnapshotTesting:
    platform: [macOS, iOS, tvOS]
    settings:
      ENABLE_BITCODE: false
      FRAMEWORK_SEARCH_PATHS: $(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks
      SWIFT_VERSION: 5.0
    scheme:
      environmentVariables:
        SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__
      testTargets: ['SnapshotTestingTests_${platform}']
    sources: [Sources]
    type: framework
  SnapshotTestingTests:
    dependencies: [{target: 'SnapshotTesting_${platform}'}]
    platform: [macOS, iOS, tvOS]
    settings:
      SWIFT_VERSION: 5.0
    sources:
      - path: Tests
        excludes:
          - LinuxMain.swift
          - '**/__Fixtures__'
          - '**/__Snapshots__'
    type: bundle.unit-test
