default_platform(:ios)

platform :ios do
    desc "Run tests"
    lane :test do
	  scan(
     	scheme: "Cooding",
      clean: true,
      output_types: "junit",
	    destination: "name=iPhone 8",
      fail_build: false
	  )
  end
end
